import { useEffect, useState, type DragEvent, type FormEvent } from 'react';
import type { ApiClient } from '../api';
import type { Card, Deck } from '../types';
import { Icon, Notice, Spinner } from './ui';

export default function DeckDetail({ api, deck, allCards, onBack, onChanged, onStudy, onMap, onCreate, onEdit, onDeleteCard }: {
  api: ApiClient; deck: Deck; allCards: Card[]; onBack: () => void; onChanged: () => Promise<void>;
  onStudy: () => void; onMap: () => void; onCreate: () => void; onEdit: (card: Card) => void; onDeleteCard: (card: Card) => void;
}) {
  const [ordered, setOrdered] = useState(deck.cards);
  const [adding, setAdding] = useState(false);
  const [selected, setSelected] = useState<string[]>([]);
  const [editing, setEditing] = useState(false);
  const [name, setName] = useState(deck.name);
  const [description, setDescription] = useState(deck.description || '');
  const [confirmDelete, setConfirmDelete] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [dragged, setDragged] = useState<string | null>(null);
  useEffect(() => { setOrdered(deck.cards); setName(deck.name); setDescription(deck.description || ''); }, [deck]);
  const run = async (operation: () => Promise<void>, message: string) => { setBusy(true); setError(null); try { await operation(); await onChanged(); } catch (e) { setError(e instanceof Error ? e.message : message); } finally { setBusy(false); } };
  const persistOrder = async (cards: Card[]) => { setOrdered(cards); await run(async () => { await api.reorderDeckCards(deck.id, cards.map((card) => card.id)); }, 'Failed to reorder cards.'); };
  const move = (index: number, delta: number) => { const target = index + delta; if (target < 0 || target >= ordered.length) return; const next = [...ordered]; [next[index], next[target]] = [next[target], next[index]]; void persistOrder(next); };
  const drop = (event: DragEvent, targetId: string) => { event.preventDefault(); if (!dragged || dragged === targetId) return; const next = [...ordered]; const from = next.findIndex((card) => card.id === dragged); const to = next.findIndex((card) => card.id === targetId); const [card] = next.splice(from, 1); next.splice(to, 0, card); setDragged(null); void persistOrder(next); };
  const save = async (event: FormEvent) => { event.preventDefault(); if (!name.trim()) return; await run(async () => { await api.updateDeck(deck.id, { name: name.trim(), description: description.trim() || null }); setEditing(false); }, 'Failed to update deck.'); };
  const candidates = allCards.filter((card) => !card.deckIds.includes(deck.id));
  return <section className="deck-detail">
    <button className="button button--ghost deck-detail__back" type="button" onClick={onBack}><Icon name="arrow-left" /> All decks</button>
    {error && <Notice tone="error" onClose={() => setError(null)}>{error}</Notice>}
    <header className="deck-detail__header"><div><span className="eyebrow">Study deck</span><h1>{deck.name}</h1><p>{deck.description || 'An ordered study set.'}</p></div><div className="deck-detail__actions"><button className="button button--secondary" type="button" onClick={() => setEditing(!editing)}><Icon name="edit" /> Edit</button><button className="button button--secondary" type="button" disabled={deck.cards.length === 0} onClick={onMap}><Icon name="map" /> Map</button><button className="button button--primary" type="button" disabled={deck.cards.length === 0} onClick={onStudy}><Icon name="study" /> Study</button></div></header>
    {editing && <form className="deck-detail__edit" onSubmit={(event) => void save(event)}><label className="field"><span className="field__label">Name</span><input value={name} onChange={(event) => setName(event.currentTarget.value)} required /></label><label className="field"><span className="field__label">Description</span><textarea rows={2} value={description} onChange={(event) => setDescription(event.currentTarget.value)} /></label><div><button className="button button--ghost" type="button" onClick={() => setEditing(false)}>Cancel</button><button className="button button--primary" type="submit" disabled={busy}>Save</button></div></form>}
    <div className="deck-detail__toolbar"><div><h2>{ordered.length} {ordered.length === 1 ? 'card' : 'cards'}</h2><p>Drag or use arrows to set the study order.</p></div><div><button className="button button--secondary" type="button" onClick={() => setAdding(!adding)} disabled={candidates.length === 0}><Icon name="add" /> Add from library</button><button className="button button--primary" type="button" onClick={onCreate}><Icon name="add" /> Create card</button></div></div>
    {adding && <div className="deck-detail__picker"><div>{candidates.map((card) => <label className="check-row" key={card.id}><input type="checkbox" checked={selected.includes(card.id)} onChange={() => setSelected((old) => old.includes(card.id) ? old.filter((id) => id !== card.id) : [...old, card.id])} /><span><strong>{card.question}</strong><small>{card.deckIds.length ? `Also in ${card.deckIds.length} ${card.deckIds.length === 1 ? 'deck' : 'decks'}` : 'Library only'}</small></span></label>)}</div><footer><button className="button button--ghost" type="button" onClick={() => { setAdding(false); setSelected([]); }}>Cancel</button><button className="button button--primary" type="button" disabled={!selected.length || busy} onClick={() => void run(async () => { await Promise.all(selected.map((id) => api.addCardToDeck(deck.id, id))); setAdding(false); setSelected([]); }, 'Failed to add cards.')}>Add {selected.length || ''}</button></footer></div>}
    <div className="deck-detail__list">{ordered.length === 0 ? <div className="empty-state"><h2>This deck is ready for cards</h2><p>Create a new card here or reuse one from your library.</p></div> : ordered.map((card, index) => <article className="deck-row" key={card.id} draggable onDragStart={() => setDragged(card.id)} onDragOver={(event) => event.preventDefault()} onDrop={(event) => drop(event, card.id)}><span className="deck-row__handle" title="Drag to reorder">⠿</span><span className="deck-row__position">{index + 1}</span><button className="deck-row__content" type="button" onClick={() => onEdit(card)}><strong>{card.question}</strong><span>{card.answer}</span></button><div className="deck-row__actions"><button className="icon-button icon-button--small" type="button" disabled={busy || index === 0} onClick={() => move(index, -1)} aria-label={`Move ${card.question} up`}>↑</button><button className="icon-button icon-button--small" type="button" disabled={busy || index === ordered.length - 1} onClick={() => move(index, 1)} aria-label={`Move ${card.question} down`}>↓</button><button className="button button--ghost button--compact" type="button" disabled={busy} onClick={() => void run(async () => { await api.removeCardFromDeck(deck.id, card.id); }, 'Failed to remove card.')}>Remove from this deck</button><button className="icon-button icon-button--small icon-button--danger" type="button" onClick={() => onDeleteCard(card)} aria-label={`Delete card: ${card.question}`}><Icon name="trash" size={15} /></button></div></article>)}</div>
    <div className="deck-detail__danger">{confirmDelete ? <div><p><strong>Delete “{deck.name}”?</strong> Cards and relationships remain in your library.</p><button className="button button--ghost" type="button" onClick={() => setConfirmDelete(false)}>Cancel</button><button className="button button--danger-ghost" type="button" disabled={busy} onClick={() => void run(async () => { await api.deleteDeck(deck.id); onBack(); }, 'Failed to delete deck.')}>{busy ? <Spinner label="Deleting deck" size="small" /> : <Icon name="trash" />} Delete deck</button></div> : <button className="button button--danger-ghost" type="button" onClick={() => setConfirmDelete(true)}><Icon name="trash" /> Delete deck</button>}</div>
  </section>;
}
